### PR TITLE
[WIP] genome-grist docs on GitHub Pages

### PR DESCRIPTION
**Pull request by mr-eyes**
I found it helpful to organize the documentation and provide some examples in a separate structured web page. So I am contributing by a Jekyll-based docs for genome-grist. Currently, it's live on [https://mr-eyes.github.io/genome-grist](https://mr-eyes.github.io/genome-grist).

### CODE REVIEW

**Comment by ctb** [comment]
hi @mr-eyes love the idea, but with one big caveat: we have mostly standardized around sphinx and mkdocs in the lab, and I am loathe to adopt Jekyll. So by all means let's write the docs in Markdown, but before merge I'd like to switch over to mkdocs. Sorry :(.

See https://github.com/spacegraphcats/spacegraphcats/pull/392 for taylor's approach to mkdocs.

**Comment by ctb** [comment]
(I've gotta maintain this stuff after you graduate, basically :)

**Comment by mr-eyes** [comment]
I got your point and will transform the PR into mkdocs with pleasure =)

**Comment by ctb** [comment]
thanks :)

**Comment by ctb** [comment]
closing in favor of #130, where I'm swiping the docs from this PR and putting them in doc/.

**Pull request closed without merging**
