### PR TITLE
[MRG] Fix `download_matching_genomes` target

### PR DESCRIPTION
**Pull request by ctb**
Fixes https://github.com/dib-lab/genome-grist/issues/119

Adds tests, too!

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review and merge @taylorreiter!

**Comment by ctb** [comment]
Tests passed! Ready for review & merge.

**Review by taylorreiter — APPROVED** [review]
well this is clever and complicated...but i think i grok whats happening. Even better than my understanding it, the tests pass 🎉 excited for this to be integrated! I think it will help genome-grist to be used in a more piecemeal approach.

**Comment by ctb** [comment]
thanks!

**Pull request merged**
