### PR TITLE
[MRG] use`sourmash prefetch` from sourmash v4.1.0

### PR DESCRIPTION
**Pull request by ctb**
Update genome-grist to use the `sourmash prefetch` code from https://github.com/dib-lab/sourmash/pull/1370, instead of its own implementation.

This also updates https://github.com/dib-lab/genome-grist/pull/76 so that the temporary directory is configurable in the conf files; briefly, you can now specify a list of possible temp directory paths, and they will be tried one at a time. Also removes a possible collision problem where if two people are working on the same sample on the same system, the first one "wins" the tempdir name; tempdirs no longer collide.

:tada: @bluegenes

### CODE REVIEW

**Comment by bluegenes** [comment]
First pass testing -- `prefetch` with a `ZipFile` index  seems to have worked!

**Comment by ctb** [comment]
Ready for review and merge, @bluegenes!

**Comment by ctb** [comment]
ping @taylorreiter @bluegenes for a quick review :)

**Review by bluegenes — APPROVED** [review]
yay 4.1!

I really like the `base_tempdir` change -- was a bit worried about potential drawbacks of just setting `/scratch`

**Comment by ctb** [comment]
yay!

**Pull request merged**
